### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by freesig** [freesig/nuitrack-rs#10]
## Goal
Take a closure and have it called by c++ who is expecting a basic c function pointer
[Turn closure into c function pointer.](https://github.com/sdroege/gstreamer-rs/blob/a1a841afc809fcf9557928867d420caaee6e8f0d/gstreamer/src/bus.rs#L52)
[Calling the c function pointer that is actually a closure.](https://github.com/sdroege/gstreamer-rs/blob/a1a841afc809fcf9557928867d420caaee6e8f0d/gstreamer/src/bus.rs#L34) 
[Thread](https://www.reddit.com/r/rust/comments/78wkvy/how_to_implementing_safe_callbacks_between_rust/) on the subject.

**Comment by freesig** [comment]
[Limitations](https://stackoverflow.com/questions/32270030/how-do-i-convert-a-rust-closure-to-a-c-style-callback)
[Trampoline function](https://stackoverflow.com/questions/8179521/implementation-of-nested-functions) I'm not sure if this is safe or just specific to gcc

**Comment by freesig** [comment]
Hey @mitchmindtree or @JoshuaBatty
You would expect to pass nuitrack-rs a closure not a vanilla fn pointer for callbacks right?
ie.
```rust
// This 
nuitrack::register_skeleton_callback(|data| //Do work);
// Not this
nuitrack::register_skeleton_callback(cb);
extern "C" fn cb(data: Data) { //Do work }
```
The second approach is way easier and safer to implement but I feel like it's too limiting for the API user.

**Comment by mitchmindtree** [comment]
Hey chap, normally I do the second way first and then downstream in some higher-level API I make the closure version using the callback version. It's a bit tricky/finicky though so don't stress if you're not sure how to go about it the closure approach, it's handy for pub APIs but might not be necessary for our use case.

**Comment by mitchmindtree** [comment]
It depends if the callback allows you to pass a pointer to some user data into the function.

E.g. in coreaudio and portaudio, when you open a stream it allows you to pass a void pointer to some user data and it will pass that user data pointer to the stream data function each time it is called. In those cases I used that user data pointer to pass the closure through to the stream data callback function. Does the nuitrack SDK allow for passing through user data? Or does it expect you to "inherit" their C++ class in a new class that has your user data and override a virtual method for the callback or something? I can imagine it might not be as simple as the standard C approaches in coreaudio and portaudio! Could you link/post the API here that they expect you to use for passing in a C function?

I haven't looked into the trampoline approach, that link is pretty interesting. Did you come across any rust implementations of a working trampoline that would solve something like this?

Yeah the global approach would probably be easy to drop in, though would probably become an issue if the API allowed for spawning more than one of the same type of stream as it might be tricky to distinguish between which stream a callback call is associated with?

**Comment by freesig** [comment]
> Yeah the global approach would probably be easy to drop in

Yeh the global approach is what I used in cpal - asio but it wasn't very satisfying.

> Does the nuitrack SDK allow for passing through user data?

Nah it doesn't

> Or does it expect you to "inherit" their C++ class in a new class that has your user data and override a virtual method for the callback or something?

I don't think that's what they want you to do. 

> Could you link/post the API here that they expect you to use for passing in a C function?

[This](http://download.3divi.com/Nuitrack/doc/classtdv_1_1nuitrack_1_1HandTracker.html#a285c41bc3bea73ece535bdda1e16a900) is the function to register the callback. It takes this [OnUpdate](http://download.3divi.com/Nuitrack/doc/classtdv_1_1nuitrack_1_1HandTracker.html#a607e8dbafa739dd1f9a6961c07e5f059) type which is just a `std::function<void (HandTrackerData::Ptr)>`.
As far as I can tell c++ [std::function](https://en.cppreference.com/w/cpp/utility/functional/function) is just a convenient way to accept many types of functions. For example you can pass it a regular C style function pointer or a c++ `std::lambda` however the lambda can't have any capture variables.

Heres an exert from their [example](http://download.3divi.com/Nuitrack/doc/nuitrack_gl_sample_2src_2main_8cpp-example.html)
```c++
void NuitrackGLSample::init(const std::string& config)
{
    // Initialize Nuitrack first, then create Nuitrack modules
    try
    {
        Nuitrack::init(config);
    }
    catch (const Exception& e)
    {
        std::cerr << "Can not initialize Nuitrack (ExceptionType: " << e.type() << ")" << std::endl;
        exit(EXIT_FAILURE);
    }
    
    // Create all required Nuitrack modules
    _depthSensor = DepthSensor::create();
    // Bind to event new frame
    _depthSensor->connectOnNewFrame(std::bind(&NuitrackGLSample::onNewDepthFrame, this, std::placeholders::_1));
    _colorSensor = ColorSensor::create();
    // Bind to event new frame
    _colorSensor->connectOnNewFrame(std::bind(&NuitrackGLSample::onNewRGBFrame, this, std::placeholders::_1));
    _outputMode = _depthSensor->getOutputMode();
    OutputMode colorOutputMode = _colorSensor->getOutputMode();
    if (colorOutputMode.xres > _outputMode.xres)
        _outputMode.xres = colorOutputMode.xres;
    if (colorOutputMode.yres > _outputMode.yres)
        _outputMode.yres = colorOutputMode.yres;
    _width = _outputMode.xres;
    _height = _outputMode.yres;
    _userTracker = UserTracker::create();
    // Bind to event update user tracker
    _userTracker->connectOnUpdate(std::bind(&NuitrackGLSample::onUserUpdate, this, std::placeholders::_1));
    _skeletonTracker = SkeletonTracker::create();
    // Bind to event update skeleton tracker
    _skeletonTracker->connectOnUpdate(std::bind(&NuitrackGLSample::onSkeletonUpdate, this, std::placeholders::_1));
    _handTracker = HandTracker::create();
    // Bind to event update Hand tracker
//-----NOTE THIS LINE
    _handTracker->connectOnUpdate(std::bind(&NuitrackGLSample::onHandUpdate, this, std::placeholders::_1));
    _gestureRecognizer = GestureRecognizer::create();
    _gestureRecognizer->connectOnNewGestures(std::bind(&NuitrackGLSample::onNewGesture, this, std::placeholders::_1));
}
```
It seems they are using [std::bind](https://en.cppreference.com/w/cpp/utility/functional/bind) to some how pass `this`. I'm not sure on how `std::bind` works. I might research this now as there might be a way to use that to pass our rust closures `user data` to the callback

**Comment by freesig** [comment]
Ok looks like it's actually possible to send through the `user_data: *mut c_void` using `std::bind` dark magic.
Thanks for the hot tips :+1:

**Comment by freesig** [comment]
Note to self: [coreaudio](https://github.com/RustAudio/coreaudio-rs/blob/master/src/audio_unit/render_callback.rs)

**Comment by freesig** [comment]
This is my attempt at a toy solution
https://github.com/freesig/nuitrack-rs/pull/12#issuecomment-440552660
