### ISSUE TITLE
nuitrack api object

### ISSUE THREAD

**Issue by freesig** [freesig/nuitrack-rs#16]
In order to verify api call order it could be useful to return an object like
```rust
let nui = nuitrack_rs::init();
nui.run();
//etc ..
```
Not sure if this is out of scope for this project though

**Comment by freesig** [comment]
Hey @mitchmindtree
What do you think about this idea?
The API is currently just a bunch of function calls wrapped around the nuitrack api. I don't track any state so it's up to the user to call them in the right order and make sure the release is called. 
If I make this object I could:
- [ ] Get a compile time call order check.
- [ ] Have a RAII style release call.

Is this beyond the scope of this crate or do you think it's a good idea? I don't think it would be much work.

**Comment by mitchmindtree** [comment]
Yeah that sounds good to me as long as it's just adding type safety and isn't overly restrictive :+1:
